### ISSUE TITLE
目前见过最好的固件

### ISSUE THREAD

**Issue by yx10010** [quanjindeng/Actions-OpenWrt#1]
大佬 你的n1跟x86的固件用的都很舒适，因为我是小白，不会自己折腾编译，在这给你提个小小的问题，就是x86版本能不能加入passwall2 ,因为我现在用的x86 2023.04.14-R23.4.1版本使用cloudflare速度测试插件给passwall优选IP无法正常运行

**Comment by quanjindeng** [comment]
优选IP用不了与passwall无关，建议你去[CloudflareSpeedTest项目](https://github.com/XIU2/CloudflareSpeedTest/issues) 看看问题怎么解决
